#!/bin/bash

source project_env
prefix=prod
is_master=$(git branch | awk '/^\* master/ { print $2 }')

if ! [ -n "$is_master" ]; then
    echo " * Only allowed at master branch. Begone!"
    exit 1
fi

function mktag() {
    tagdate=$(date '+%Y%m%d')
    tagbasename=$prefix-$tagdate

    nextver=$[ $(git tag -l "$tagbasename.*" | wc -l) + 1]

    tagname="$tagbasename.$nextver"
    ver="$tagdate.$nextver"
    echo $ver > project_version

    if ! git tag -a -m "Releasing production version - $tagname" $tagname; then
        rc=$?
        echo " * setting tag $tagname failed"
        exit $rc
    fi
    if ! git push origin HEAD:master $tagname; then
        rc=$?
        echo " * pushing tag $tagname failed"
        exit $rc
    fi
}

if ! git fetch -t;
then
    rc=$?
    echo " * git fetch failed"
    exit $rc
fi


if [ -n "$1" ];
then
    y=$1
else
    echo -n "Create production release [y/N]? "; read y
fi

[ "x$y" == "xy" ] && mktag

